Add guest post on TS
grouparoo/www.grouparoo.com pull request #19
Opened 2020-10-13 20:45 UTC by NotWoods

Let me know what needs to be tweaked here. I added a bit at the top based on similar guest post text [in CSS Tricks](https://css-tricks.com/templating-languages-and-wordpress/).

Once this is merged a hacktoberfest-accepted label would be a nice to have :)

2020-10-13 21:25 UTC, evantahler commented
That was ridiculously fast! 

The post looks great! I want to do https://github.com/grouparoo/www.grouparoo.com/issues/18 first, to add a little more author information.  Thanks for providing your photo... would you mind writing a short description for yourself in a comment on https://github.com/grouparoo/www.grouparoo.com/issues/18.

This way, the "The following is a guest post..." section shouldn't be needed, as you'll have more rich "Author" area on the page.

2020-10-13 21:26 UTC, evantahler commented
Also, I'm glad you found this site easy to work with! If you've got any suggestions about running the project, please let me know!

2020-10-13 22:47 UTC, evantahler commented
ok! https://github.com/grouparoo/www.grouparoo.com/pull/20 is merged in and now there are `<AuthorBox />` components on the pages.  If you rebase this PR against the `master` branch, you can add yourself to [`data/authors.ts`](https://github.com/grouparoo/www.grouparoo.com/blob/master/data/authors.ts) so your'll have a richer entry about yourself on the post & author page.  

Please add your image to `/public/images/authors` rather than `/public/images/team`

Thank you!

2020-10-13 23:50 UTC, NotWoods commented
Moved stuff around! The repo was very easy to get started with, the info in the README made it easy to get going

2020-10-14 01:05 UTC, evantahler commented on components/blog/authorBox.tsx
>            />
Thanks!

2020-10-14 01:06 UTC, evantahler approved these changes

2020-10-14 01:36 UTC, andyjih requested changes
Looks great! Just a small typo

2020-10-14 01:36 UTC, andyjih commented on pages/blog/any-wreaks-havoc-on-overloads.mdx
> +TypeScript has another [neat feature called function overloads](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads). Some JavaScript functions return different results b
"to he" -> "to the"

2020-10-14 01:47 UTC, andyjih approved these changes

2020-10-14 01:47 UTC, andyjih commented
👍

2020-10-14 02:18 UTC, merged