Code Config Docs
grouparoo/www.grouparoo.com pull request #200
Opened 2021-02-09 12:22 UTC by seancdavis

WIP

2021-02-11 20:53 UTC, andyjih requested changes
Great work! I had some comments. I think the intro section to most of the configuration docs has the same typo of "This guide is covers" so I stopped commenting on every single file.

2021-02-11 20:53 UTC, andyjih commented on pages/docs/config.mdx
> +<Button className="mb-4" variant="outline-primary">
I think this button is missing a link.

2021-02-11 20:53 UTC, andyjih commented on pages/docs/config/apps/community.mdx
> +    This guide is covers configuration with Grouparoo's Code Config, which is
"This guide is covers" 
->
"This guide covers"

2021-02-11 20:53 UTC, andyjih commented on pages/docs/config/apps/community.mdx
> +      initialized the Grouparoo application locally
"initialized"
->
"initialize"

2021-02-11 20:53 UTC, andyjih commented on pages/docs/config/apps/enterprise.mdx
> +    This guide is covers configuration with Grouparoo's Enterprise Edition. If
"This guide is covers" 
-> 
"This guide covers"

2021-02-11 21:08 UTC, andyjih commented on pages/docs/config.mdx
> +- [Adding Apps](/docs/config/apps/enterprise)
Per your "Discrepancy in Steps" note, I wonder if we add some notes here about Running and Deploying before using the UI to configure.

2021-02-12 01:41 UTC, evantahler reviewed
Awesome work with a lot of great updates! 

* Cleaning Up Frontmatter 👍 
* Nav always highlights parent 👍 
* The overall changes 👍

General Comments:

* We talked a bit about how to toggle between code-config and ui-config.  I think the choice you made to always default to code-config is good, and highlights the path we think most people will be taking
* None of the code-config examples show an actual code-config JS file.  Should they?
* On almost all of the pages you have the `Validating and Applying your Config` section - make that a shared component!  Also, perhaps it's a card or some other style so it stands apart.

2021-02-12 01:41 UTC, evantahler commented on data/docs-redirects.js
> +];
Nice!

2021-02-12 01:41 UTC, evantahler commented on pages/docs/config.mdx
> +<Button className="mb-4" variant="outline-primary">
Also... it seems odd to have both a button and a link to the same page right near each other.

2021-02-12 01:41 UTC, evantahler commented on pages/docs/config/apps/community.mdx
> +      use the Enterprise Apps Guide
There's a missing space on all the config pages `you may wishto use`

2021-02-12 01:41 UTC, evantahler commented on pages/docs/config/apps/community.mdx
> +      use the Enterprise Apps Guide
Another spot for a shared component maybe?

2021-02-12 01:41 UTC, evantahler commented on pages/docs/support/permissions.mdx
>  ---
I don't think `docs/support/permissions` is just for enterprise users.  There are still teams and teamMembers in the community edition, and API keys.   It's OK to leave in the support section, but I'd remove the "Enterprise" title-tag

2021-02-12 15:28 UTC, seancdavis commented
Lots of updates here:

- Looks like @andyjih fixed all my stupid typos. (Slow down, Sean!) Thanks, Andy!
- Added a handful of shared components.
- Added code examples to each of the community pages.
- Removed "Enterprise" from permissions page. That was lingering from a previous story.
- Fixed the "Deployment" title, too.

2021-02-12 17:12 UTC, merged