178045142 - Adjust top level nav to include integrations
grouparoo/www.grouparoo.com pull request #428
Opened 2021-05-06 01:13 UTC by tealjulia

TO DO:
* Adjust vertical alignment
* Remove integrations from navigation

DONE:
* Add nav-link class to navigation links
* Add top level Integrations link

2021-05-07 02:47 UTC, evantahler requested changes
Good start!

1. [to-check] I think we wanted the Github button to take folks to the github repo, in an attempt to prove we are open source and ask them to star it.  I defer to @andyjih if that's still the plan
2. [idea] With the wider spacing between links, it /almost/ looks like the nav is center-aligned, but not quite.  If the intent was to add more padding, perhaps center aligning might help 
3. [bug] On the "tablet" size screen, a few things are wonky (attached):
   1. The Github button goes to 2-lines
   2. The "get started" button is out-of-frame
   3. You may need to hide an element to make everything fit.  We do this now, dropping "community" when the screen gets too small, but we aren't yet on mobile to get the hamburger.
4. [bug] The hover states are a bit off-center (attached)
<img width="445" alt="Screen Shot 2021-05-06 at 7 39 11 PM" src="https://user-images.githubusercontent.com/303226/117390913-d3212880-aea3-11eb-8111-1dd1b97cc6d2.png">

<img width="1127" alt="Screen Shot 2021-05-06 at 7 39 48 PM" src="https://user-images.githubusercontent.com/303226/117390909-d0bece80-aea3-11eb-9ca9-0df297e454e5.png">

2021-05-07 03:20 UTC, andyjih commented
> 1. [to-check] I think we wanted the Github button to take folks to the github repo, in an attempt to prove we are open source and ask them to star it.  I defer to @andyjih if that's still the plan

Correct-- the link should continue to go to the github repo please!

Also, the nav feels a bit crowded now, so an idea is to remove the link to the blog from the top-nav. We should keep it in the footer though.  

Looks good!

2021-05-08 02:22 UTC, evantahler requested changes
Other than that broken link, 👍

2021-05-08 02:22 UTC, evantahler commented on components/navigation.tsx
> +                        <Link href="/integrations/destinations/zendexk">
Typo!

2021-05-10 18:00 UTC, evantahler approved these changes

2021-05-11 14:32 UTC, evantahler requested changes
There's something not quite right with git again - there are too many commits/changes here.  For example, the layouts for the Comparison and Category pages have already been merged in, along with the blog post.

2021-05-11 17:04 UTC, tealjulia commented
Worked with @seancdavis to fix commit history and we ended up switching to a new branch/PR

2021-05-11 17:04 UTC, closed without merging