Config UI Docs
grouparoo/www.grouparoo.com pull request #533
Opened 2021-06-22 15:37 UTC by seancdavis

WIP ...

2021-06-25 01:02 UTC, evantahler reviewed
So much good stuff here!  This is really good, and I'm still reading though it. 

Some comments below on the structure.  

General Questions:
* From the bug bash, there's some clarity we need about installing plugins (and how the app is a separate thing)
* You hid the code config docs (which I agree with!) but ... how can I get to them?

2021-06-25 01:02 UTC, evantahler commented on pages/docs/config.mdx
> +Config UI is the recommended way to configure your Grouparoo data. It requires the [@grouparoo/ui-config](https://www.npmjs.com/package/@grouparoo/ui-config) plugin. This is included by default when
> If you don't have it as a dependency because you are updating from an older version of Grouparoo, you can install it with the `install` command...

2021-06-25 01:02 UTC, evantahler commented on data/docs-nav.ts
> +    children: [
Can these not be expanded until you click into the enterprise section?
<img width="192" alt="Screen Shot 2021-06-24 at 5 55 32 PM" src="https://user-images.githubusercontent.com/303226/123352999-61657280-d515-11eb-895c-dc0a5d02aa6c.png">

2021-06-25 01:02 UTC, evantahler commented on pages/docs/config/apps.mdx
> +
This could be shared maybe?

2021-07-07 19:18 UTC, seancdavis commented on pages/docs/config/apps.mdx
> +
Done!

2021-07-07 19:18 UTC, seancdavis commented on data/docs-nav.ts
> +    children: [
Great idea!

2021-07-07 19:19 UTC, seancdavis commented on data/docs-nav.ts
> +    children: [
This also made it much more appropriate to add the code config links back to the navigation. Now you can get to them under "Code Config" in Step 2.

2021-07-07 19:19 UTC, seancdavis commented
Should all be addressed and up to date.

2021-07-07 21:03 UTC, evantahler requested changes
This is just about done!

Some minor notes below

2021-07-07 21:03 UTC, evantahler commented on components/docs/tableOfContents.tsx
> +  const isActive = router.asPath.includes(item.path);
👍

2021-07-07 21:03 UTC, evantahler commented on package-lock.json
>          "react": ">=16.8.0"
Why are there `package-lock.json` changes if there are no `package.json` changes?

2021-07-07 21:03 UTC, evantahler commented on pages/docs/config.mdx
> +date: "2021-06-23"
Note to future me: Can we determine these dates automatically from the file's update time or someting?

2021-07-07 21:03 UTC, evantahler commented on pages/docs/config.mdx
> +If you're using Grouparoo's Enterprise Edition, you can also configure the application through the UI. However, we don't recommend this for first time users, as it does not provide the ability to tes
This sentence is a bit odd - I don't know if we want to say that Enterprise Edition is "worse" in some way.  Perhaps:

> If you're using Grouparoo's Enterprise Edition, we recommend that you follow the same workflow by creating and testing your config files locally first before deploying changes with `@grouparoo/ui-config`.  That said, you are also able to create new config objects directly on your production server as well, using live data immediately.  [See here](/docs/running/ui-enterprise) for more information on configuration objects with Grouparoo's Enterprise Edition.

2021-07-07 21:03 UTC, evantahler commented on pages/docs/config.mdx
> +    $ grouparoo install @grouparoo/ui-config
I'd want to call out even moreso that you might not need to do this:

```bash
# If you are upgrading from Grouparoo v0.4.x or earlier
$ grouparoo install @grouparoo/ui-config
```

2021-07-07 21:03 UTC, evantahler commented on pages/docs/config/apps.mdx
> +Apps are enabled by installing plugins. Fortunately, Grouparoo's UI Config helps you install plugins on the fly. Apps from installed plugins will have an orange badge and are ready to be installed im
Do we need to add any notes about:
* Your package.json will change; we are doing "npm install" behind the scenes 
* You need to be online
* If something goes wrong, turn off the server and try the Grouparoo CLI

2021-07-07 21:03 UTC, evantahler commented on pages/docs/config/profiles.mdx
> +Grouparoo's UI Config will write a file to your local filesystem based on your inputs. The file will be placed at `config/development/profiles.json` in your Grouparoo project. It will contain a list
These profiles are only used when running `grouparoo config` - they will not be loaded into your deployed application.

2021-07-07 21:03 UTC, evantahler commented on pages/whats-new/2021-03-09-grouparoo-generate.mdx
> +The generate command uses your input to write a configuration file to your file system. You can then use this file to configure the various objects in Grouparoo, like [Apps](/docs/config/code-config/
Thank you for updating the links in old posts/what's new!

2021-07-08 15:42 UTC, seancdavis commented on package-lock.json
>          "react": ">=16.8.0"
Ugh. Rebasing. I'll put it back.

2021-07-08 15:46 UTC, seancdavis commented on pages/docs/config.mdx
> +date: "2021-06-23"
Could be a fun GitHub (or CI) action — look at MD(X) files changed in the PR and update dates in those files.

2021-07-08 15:46 UTC, seancdavis commented on pages/docs/config.mdx
> +    $ grouparoo install @grouparoo/ui-config
Great idea!

2021-07-08 15:57 UTC, seancdavis commented on pages/docs/config/apps.mdx
> +Apps are enabled by installing plugins. Fortunately, Grouparoo's UI Config helps you install plugins on the fly. Apps from installed plugins will have an orange badge and are ready to be installed im
Great points!

2021-07-13 19:12 UTC, evantahler approved these changes

2021-07-13 19:16 UTC, merged