url and email validation
grouparoo/www.grouparoo.com pull request #536
Opened 2021-06-23 01:02 UTC by tealjulia

- Uses validator npm package to validate emails and urls
- Checks emails against array of "illegal" domains

There are still some iffy urls that can get through?  We can tighten it further if needed, but I think this should eliminate most bots, I've been using this npm package for a while for form validation.

If this is acting how you'd hoped @andyjih, I'll add testing.

2021-06-23 01:05 UTC, andyjih commented
@tealjulia This looks great! 👍

2021-06-23 19:14 UTC, evantahler requested changes
Code-wise, this looks great (other than a few things to remove)!

I'm a little worried about the fact that this PR means that people who don't have a 'work' email address can't contact us.  It seems unlikely, but possible?  Either way, maybe if the error message was changed from:

> 
> Please enter a valid work email.

to

> Please enter a valid work email.  If you are still having trouble you can reach us by email at hello@grouparoo.com

so at least we give folks /some/ way of getting in touch. 
cc @andyjih

2021-06-23 19:14 UTC, evantahler commented on utils/inflectors.ts
> +import validator from "validator";
Doesn't look to be in use

2021-06-23 19:14 UTC, evantahler commented on pages/trial.tsx
> +    validator.isURL(data.companyWebsite);
I think these don't actually effect the method?

2021-06-23 20:02 UTC, andyjih commented
> Code-wise, this looks great (other than a few things to remove)!
> 
> I'm a little worried about the fact that this PR means that people who don't have a 'work' email address can't contact us. It seems unlikely, but possible? Either way, maybe if the error message was changed from:
> 
> > Please enter a valid work email.
> 
> to
> 
> > Please enter a valid work email.  If you are still having trouble you can reach us by email at [hello@grouparoo.com](mailto:hello@grouparoo.com)
> 
> so at least we give folks /some/ way of getting in touch.
> cc @andyjih

I disagree, and I don't think adding the extra messaging is necessary. We also have lots of other ways for them to get in touch if they so choose. (slack community, github, they can find the help@ email elsewhere as well). I'd prefer to keep these forms focused on our target persona e.g. people working at companies.

2021-06-23 20:06 UTC, tealjulia commented
> > Code-wise, this looks great (other than a few things to remove)!
> > I'm a little worried about the fact that this PR means that people who don't have a 'work' email address can't contact us. It seems unlikely, but possible? Either way, maybe if the error message was changed from:
> > > Please enter a valid work email.
> > 
> > 
> > to
> > > Please enter a valid work email.  If you are still having trouble you can reach us by email at [hello@grouparoo.com](mailto:hello@grouparoo.com)
> > 
> > 
> > so at least we give folks /some/ way of getting in touch.
> > cc @andyjih
> 
> I disagree, and I don't think adding the extra messaging is necessary. We also have lots of other ways for them to get in touch if they so choose. (slack community, github, they can find the help@ email elsewhere as well). I'd prefer to keep these forms focused on our target persona e.g. people working at companies.

I'd wondered about that.  My thought was a generic help line under the heading or at the bottom of the page in a smaller font "If you need assistance with registration, please reach out at hello@grouparoo.com"...?

2021-06-23 20:14 UTC, evantahler commented
I like the smaller note at the bottom if @andyjih is OK with it!

2021-06-23 20:32 UTC, andyjih commented
Sure, a smaller note at the bottom like what we have on the /meet page works for me. We can use the same copy. "For all other inquires, please email help@grouparoo.com"

2021-06-24 16:12 UTC, andyjih approved these changes
lgtm!

2021-06-24 16:15 UTC, evantahler approved these changes

2021-06-24 16:16 UTC, merged