add new plugins to www
grouparoo/www.grouparoo.com pull request #633
Opened 2021-08-30 18:20 UTC by tealjulia

2021-08-30 20:48 UTC, tealjulia commented on data/plugins/calculated-property.ts
> +};
This file generates the manifest entry for calculated properties... it is not imported into the `/integrations` page at all but is still needed for the manifest.

2021-08-30 20:49 UTC, tealjulia commented on data/plugins/index.ts
> +  Mixpanel,
Adds Mailjet and Mixpanel to the `/integrations` page

2021-08-30 23:04 UTC, bleonard commented
Is it true that we should wait to merge this until the 0.6 when the plugins are released? I think that's right because UI config reads the manifest.

2021-08-31 14:48 UTC, tealjulia commented
> Is it true that we should wait to merge this until the 0.6 when the plugins are released? I think that's right because UI config reads the manifest.

Sounds right.  I just figured out why it was being erased from the manifest every time I pushed.  I'm thinking this commit should have it good to go!

2021-08-31 16:51 UTC, andyjih requested changes
Looks good! The only note is that the calculated property image looks a bit skewed. 

![Screen Shot 2021-08-31 at 9 49 27 AM](https://user-images.githubusercontent.com/633226/131543901-370b5c88-5899-40b2-8522-378aed83d880.png)

2021-08-31 17:41 UTC, tealjulia commented
> Looks good! The only note is that the calculated property image looks a bit skewed.
> 
> ![Screen Shot 2021-08-31 at 9 49 27 AM](https://user-images.githubusercontent.com/633226/131543901-370b5c88-5899-40b2-8522-378aed83d880.png)

Thanks!  I think we actually don't want it to display calculated properties at all on this page.  I did make it square to display properly in UI config, but I also removed it from the `/integrations` page.

2021-08-31 17:59 UTC, andyjih approved these changes

2021-09-01 18:07 UTC, merged