Profiles to Records
grouparoo/www.grouparoo.com pull request #717
Opened 2021-10-12 16:17 UTC by krishnaglick

Replace all the words and images to be ready for Models & Records

## Notes

* I could not update Eloqua images because I could not log in
* I could not update Pardot images because I could not log in

## Checklists

### Development

- [ ] Application changes have been tested appropriately

### Impact

- [ ] Code follows company security practices and guidelines
- [ ] Security impact of change has been considered
- [ ] Performance impact of change has been considered
- [ ] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

>

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [ ] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-10-12 18:32 UTC, evantahler commented on data/plugins/redshift.ts
> +      imageSrc: "/images/home/integrations/redshift/add-redshift-app.png",
We were using Postgres images for Redshift 😓 ...

2021-10-12 22:51 UTC, evantahler commented
@krishnaglick I've got all the images updated for the "marketing" (homepage, solutions, industries, and integrations) part of the site 🥳!   Every image is now the same aspect ratio and in the browser chrome!

There's a large photoshop file [here](https://drive.google.com/drive/folders/0AAueszLSSDzEUk9PVA) with the guides and images if we need to create these again.

2021-10-13 20:18 UTC, krishnaglick commented
Unsure who else we should put on this @evantahler 
Brian and Andy?

2021-10-13 21:30 UTC, evantahler commented
This is one hell of a PR!  

Adding @andyjih because he's better at words than me.

2021-10-13 21:34 UTC, evantahler commented on data/cli-commands.json
> +        "description": "Skip exporting the records",
```suggestion
        "description": "Skip exporting the Records",
```

2021-10-14 16:07 UTC, andyjih requested changes
Phew! Impressive work. 💪🏽 

 I made a handful of comments/edits, but nothing major.

2021-10-14 16:07 UTC, andyjih commented on components/docs/plugins/createApp.tsx
> +          Note that every Generator requires an <code>id</code> argument. It is
Why is Generator capitalized?

2021-10-14 16:07 UTC, andyjih commented on components/docs/plugins/querySource.tsx
> +        description: `The name of the ${column} to use as the High Watermark.`,
Not sure if "High Watermark" needs to be capitalized. I'm feeling like we need to update our style guide to decide what warrants capitalization or not.

2021-10-14 16:07 UTC, andyjih commented on components/documents/data-sync-organization.mdx
> +No App stands alone. The goal is to create value for the whole organization. These last few tenants help achieve the promise of a well-built data sync App.
```suggestion
No app stands alone. The goal is to create value for the whole organization. These last few tenants help achieve the promise of a well-built data sync app.
```

2021-10-14 16:07 UTC, andyjih commented on components/documents/data-sync-organization.mdx
> +Because fast iteration leads to business success, the organizational value of a data sync App is a function of how quickly it enables you to respond to new data requests. Change is inevitable, so mak
```suggestion
Because fast iteration leads to business success, the organizational value of a data sync app is a function of how quickly it enables you to respond to new data requests. Change is inevitable, so make them zero point stories.
```

2021-10-14 16:07 UTC, andyjih commented on components/documents/data-sync-organization.mdx
> +This kind of App is different from your normal product in many ways, right? Look at all these rules!
```suggestion
This kind of app is different from your normal product in many ways, right? Look at all these rules!
```

2021-10-14 16:07 UTC, andyjih commented on components/documents/data-sync-organization.mdx
> +The best results come from treating this App just like all the other product-focused codebases. Manage data sync just like you would any other part of your stack. You test the configuration, check it
```suggestion
The best results come from treating this app just like all the other product-focused codebases. Manage data sync just like you would any other part of your stack. You test the configuration, check it into git, run it on CI, review, merge, and deploy.
```

2021-10-14 16:07 UTC, andyjih commented on components/documents/data-sync-organization.mdx
> +Creating a robust data sync App is the best way to bridge the gap. It’s a stop-over on this data journey that we can use to discuss requirements concretely. Marketers understand how the data properti
```suggestion
Creating a robust data sync app is the best way to bridge the gap. It’s a stop-over on this data journey that we can use to discuss requirements concretely. Marketers understand how the data properties in the App end up in their tool. Engineers understand how queries create these properties. Now, both can focus on the correct data definition and not worry always be worrying about the mechanism.
```

2021-10-14 16:07 UTC, andyjih commented on data/cli-commands.json
> +    "description": "Install a grouparoo Plugin (via npm install) and enable it.  Use package@version for a specific version or tag",
```suggestion
    "description": "Install a Grouparoo Plugin (via npm install) and enable it.  Use package@version for a specific version or tag",
```

2021-10-14 16:07 UTC, andyjih commented on data/legal/privacy.md
> +- To comply with legal obligations and legal process and to protect our rights, privacy, safety, or Property, and/or that of our affiliates, you, or other third parties.
```suggestion
- To comply with legal obligations and legal process and to protect our rights, privacy, safety, or property, and/or that of our affiliates, you, or other third parties.
```

2021-10-14 16:07 UTC, andyjih commented on data/legal/privacy.md
> +- **Legal Requirements:** If required to do so by law or in the good faith belief that such action is necessary to (i) comply with a legal obligation, including to meet national security or law enfor
```suggestion
- **Legal Requirements:** If required to do so by law or in the good faith belief that such action is necessary to (i) comply with a legal obligation, including to meet national security or law enforcement requirements, (ii) protect and defend our rights or property, (iii) prevent fraud, (iv) act in urgent circumstances to protect the personal safety of users of the Service, or the public, or (v) protect against legal liability.
```

2021-10-14 16:07 UTC, andyjih commented on data/plugins/mixpanel.ts
> +        "Grouparoo keeps your User Records data in Mixpanel updated in real-time",
```suggestion
        "Grouparoo keeps your User Profiles data in Mixpanel updated in real-time",
```

2021-10-14 16:07 UTC, andyjih commented on data/plugins/mixpanel.ts
> +        "Empower your sales team to make the right actions based on analytics now that all of your User Records information is up-to-date in Mixpanel",
```suggestion
        "Empower your sales team to make the right actions based on analytics now that all of your User Profiles information is up-to-date in Mixpanel",
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/cli/config.mdx
> +There are many templates which you can use to generate from, depending on the plugins you have installed. You can use the `--list` flag to see available templates and Filter the results. For example:
```suggestion
There are many templates which you can use to generate from, depending on the plugins you have installed. You can use the `--list` flag to see available templates and filter the results. For example:
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/cli/config.mdx
> +  * mapping - The Mapping between a column in this table and a Grouparoo Property, e.g: `--mapping "id=user_id"`
```suggestion
  * mapping - The mapping between a column in this table and a Grouparoo Property, e.g: `--mapping "id=user_id"`
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/cli/config.mdx
> +Certain plugins may provide additional generation options to help you generate many objects at once. For example, if you have a valid [`App`](/docs/config/code-config/apps) already configured and app
```suggestion
Certain plugins may provide additional generation options to help you generate many objects at once. For example, if you have a valid [`App`](/docs/config/code-config/apps) already configured and applied, Grouparoo can inspect that App and generate a Source and Properties automatically for you. Batch generation is signified by using the `--from` flag, and potentially the `--with`, `--mapping` and `--high-water-mark` flags as well.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/cli/config.mdx
> +  --mapping 'id=user_id' \ # How the Mapping should shake out
```suggestion
  --mapping 'id=user_id' \ # How the mapping should shake out
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/config/code-config/destinations.mdx
> +The Generator attempts to make a _reasonable_ guess at the values in the config file it generated (in the `config/destinations` directory). There are ellipses (`"..."`) in the places in which it coul
```suggestion
The generator attempts to make a _reasonable_ guess at the values in the config file it generated (in the `config/destinations` directory). There are ellipses (`"..."`) in the places in which it couldn't make a reasonable guess. In the example above, after generating a Postgres App, all but `appId`, `groupId`, and `options.listId` were pre-populated.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/config/code-config/groups.mdx
> +This Group would contain records with an email address that is not `@grouparoo.com` that have made a purchase in the last 15 days, have a lifetime value over $3000, and are subscribed to our newslett
```suggestion
This Group would contain Records with an email address that is not `@grouparoo.com` that have made a purchase in the last 15 days, have a lifetime value over $3000, and are subscribed to our newsletter.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/config/code-config/groups.mdx
> +While a great deal of the value of Grouparoo comes from our Calculated Groups, Manual Groups are still valuable in certain circumstances. Manual Groups are Groups of records where you manually add or
```suggestion
While a great deal of the value of Grouparoo comes from our Calculated Groups, Manual Groups are still valuable in certain circumstances. Manual Groups are Groups of Records where you manually add or remove Records from the Group.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/config/destinations.mdx
> +Here's how to send records, groups, and Record properties to destinations:
```suggestion
Here's how to send Records, Groups, and Record properties to destinations:
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/development.mdx
> +# On OSX/ZSH, we recommend installing Oh My ZSH (https://github.com/ohmyzsh/ohmyzsh) and enabling the nvm Plugin
```suggestion
# On OSX/ZSH, we recommend installing Oh My ZSH (https://github.com/ohmyzsh/ohmyzsh) and enabling the nvm plugin
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/getting-started/product-concepts.mdx
> +Filters are a series of rules used to Filter data into some desired subset.
```suggestion
Filters are a series of rules used to filter data into some desired subset.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-braze.mdx
> +- **Sync** (`sync`): Add, update, and remove records as needed.
```suggestion
- **Sync** (`sync`): Add, update, and remove Records as needed.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-braze.mdx
> +- **Additive** (`additive`): Add and update records as needed, but do not remove anybody.
```suggestion
- **Additive** (`additive`): Add and update Records as needed, but do not remove anybody.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-braze.mdx
> +- **Enrich** (`enrich`): Only update records that already exist in the Destination. Do not add or remove anybody.
```suggestion
- **Enrich** (`enrich`): Only update Records that already exist in the Destination. Do not add or remove anybody.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-intercom.mdx
> +- **Sync** (`sync`): Add, update, and remove records as needed.
```suggestion
- **Sync** (`sync`): Add, update, and remove Records as needed.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-intercom.mdx
> +- **Additive** (`additive`): Add and update records as needed, but do not remove anybody.
```suggestion
- **Additive** (`additive`): Add and update Records as needed, but do not remove anybody.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-intercom.mdx
> +- **Enrich** (`enrich`): Only update records that already exist in the Destination. Do not add or remove anybody.
```suggestion
- **Enrich** (`enrich`): Only update Records that already exist in the Destination. Do not add or remove anybody.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-marketo.mdx
> +- **Sync** (`sync`): Add, update, and remove records as needed.
```suggestion
- **Sync** (`sync`): Add, update, and remove Records as needed.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-marketo.mdx
> +- **Additive** (`additive`): Add and update records as needed, but do not remove anybody.
```suggestion
- **Additive** (`additive`): Add and update Records as needed, but do not remove anybody.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-marketo.mdx
> +- **Enrich** (`enrich`): Only update records that already exist in the Destination. Do not add or remove anybody.
```suggestion
- **Enrich** (`enrich`): Only update Records that already exist in the Destination. Do not add or remove anybody.
```

2021-10-14 16:07 UTC, andyjih commented on pages/solutions/modern-data-stack.mdx
> +Your data no longer uniquely lives in customer support, sales, or marketing tools. You now have the full Record of what has been going on inside of those tools in a format that is queryable.
```suggestion
Your data no longer uniquely lives in customer support, sales, or marketing tools. You now have the full record of what has been going on inside of those tools in a format that is queryable.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-salesforce.mdx
> +- **Sync** (`sync`): Add, update, and remove records as needed.
```suggestion
- **Sync** (`sync`): Add, update, and remove Records as needed.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-salesforce.mdx
> +- **Additive** (`additive`): Add and update records as needed, but do not remove anybody.
```suggestion
- **Additive** (`additive`): Add and update Records as needed, but do not remove anybody.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/plugins/grouparoo-salesforce.mdx
> +- **Enrich** (`enrich`): Only update records that already exist in the Destination. Do not add or remove anybody.
```suggestion
- **Enrich** (`enrich`): Only update Records that already exist in the Destination. Do not add or remove anybody.
```

2021-10-14 16:07 UTC, andyjih commented on pages/docs/running/ui-enterprise/groups.mdx
> +Each Rule has an operator — a logical statement to Filter records. A Record must match every Rule to be included in the Group.
```suggestion
Each Rule has an operator — a logical statement to filter records. A Record must match every Rule to be included in the Group.
```

2021-10-14 16:57 UTC, andyjih approved these changes

2021-10-14 17:34 UTC, evantahler approved these changes
Let's ship it!

2021-10-14 17:39 UTC, merged