Legaldocs
grouparoo/www.grouparoo.com pull request #719
Opened 2021-10-14 02:08 UTC by andyjih

## Change description

Legal docs

## Related issues

Does this PR fix a Github Issue?

N/A

## Checklists

### Development

- [ ] Application changes have been tested appropriately

### Impact

- [ ] Code follows company security practices and guidelines
- [ ] Security impact of change has been considered
- [ ] Performance impact of change has been considered
- [ ] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

>

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [ ] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-10-14 15:51 UTC, evantahler requested changes

2021-10-14 15:51 UTC, evantahler commented on public/sitemap.xml
> +    >https://www.grouparoo.com/legal/terms-20211013</loc><changefreq
We probably don't want the old terms in the sitemap

2021-10-14 15:51 UTC, evantahler commented on pages/legal/terms-20211013.tsx
> +        <title>Grouparoo Master Terms and Conditions</title>
Probably should have the old date in the title

2021-10-14 15:51 UTC, evantahler commented on data/legal/data-processing-addendum.md
> +   3.2.10. For the purposes of Annex II, data importer has implemented and will maintain appropriate technical and organizational measures to protect the security, confidentiality and integrity of Cu
So... there is no `/legal/security` page.  That's why the test is failing.

2021-10-14 15:53 UTC, evantahler requested changes
There's no way to get to the `/legal/data-processing-addendum` page from any link or the footer. 

Maybe we need a `/legal` root page with links to all the other legal docs?

2021-10-14 20:29 UTC, bleonard commented on data/legal/terms-20211013.md
> +# Grouparoo Master Terms and Conditions
If this isn't an actual url, I think you might want to put it in `components/documents/terms-20211013.md`
Then you can load that from the main page.
It also wouldn't show up in the sitemap.

2021-10-14 20:31 UTC, bleonard commented on data/legal/terms-20211013.md
> +# Grouparoo Master Terms and Conditions
actually maybe that's already kinda like that. nevermind

2021-10-22 16:18 UTC, andyjih commented
> There's no way to get to the `/legal/data-processing-addendum` page from any link or the footer.
> 
> Maybe we need a `/legal` root page with links to all the other legal docs?

We will only link to the data processing addendum from order forms/contracts that we send to people.

2021-10-27 21:06 UTC, bleonard approved these changes
lgtm!
(legal is good to me)

2021-10-28 21:58 UTC, evantahler requested changes

2021-10-28 21:58 UTC, evantahler commented on data/legal/security.md
> +Coming soon
How is this page different from https://www.grouparoo.com/docs/support/security?

2021-10-28 21:58 UTC, evantahler commented on utils/sitemap.ts
> +      !p.includes("/terms-")
```suggestion
      !p.includes("/legal/terms-")
```

2021-10-28 21:58 UTC, evantahler commented on components/footer.tsx
> +                  <Link href="/legal/terms">
Missing a `<br />`

2021-10-28 21:58 UTC, evantahler commented
Some other misc things to point out:

The address is code :D 
<img width="844" alt="Screen Shot 2021-10-28 at 2 56 27 PM" src="https://user-images.githubusercontent.com/303226/139342057-88040661-c767-4185-8984-810d9bd0ffd4.png">

The tables on this page should probably have some padding between each cell
<img width="677" alt="Screen Shot 2021-10-28 at 2 57 38 PM" src="https://user-images.githubusercontent.com/303226/139342090-cd241f18-4191-457d-a04d-b5dc4fd50877.png">

2021-10-28 21:59 UTC, evantahler commented
<img width="151" alt="Screen Shot 2021-10-28 at 2 57 51 PM" src="https://user-images.githubusercontent.com/303226/139342132-b8563cb6-3cb0-45a7-bf33-75f25485f6dc.png">

2021-10-28 22:00 UTC, evantahler commented on data/legal/data-processing-addendum.md
> +   3.4. With respect to transfers from Customer to Grouparoo of Customer Personal Data originating from the United Kingdom, the parties agree to comply with the UK SCCs, which are incorporated herein
> Appendix 2 to the UK SCCs, the security measures are as described at Grouparoo’s [Security Page](/legal/security)or as otherwi

Missing a space after the link

2021-10-28 22:55 UTC, andyjih commented on data/legal/security.md
> +Coming soon
This page will cover our hosted security policies and practices. Will be updating this in the next couple weeks.

2021-10-28 23:54 UTC, evantahler approved these changes
👩‍⚖️

2021-10-28 23:54 UTC, merged