NextJS Blog Post
grouparoo/www.grouparoo.com pull request #722
Opened 2021-10-15 15:48 UTC by krishnaglick

2021-10-15 17:47 UTC, evantahler requested changes
I like the intro giving some personal and historic context!  I think you may have buried the lede a bit though.  All the way at the bottom is what the blog post is actually talking about - how Grouparoo uses Next's page hydration, and how that separate server-side contexts don't match with client contexts.  I'd suggest starting with an intro about the problem, and then getting into the history.

Your examples are good, but they are lacking context:
* Are these examples the problem code or the solution code?
* Where are these files?  Are they next,js pages? 

I think I'd want the blog post to end with an example that does work and shows how I could hydrate a context from data given to the page in `getInitialProps()`

Also, you may wan to link out to the next.js docs so people can learn more about why Next is different and why using getInitialProps is helpful

2021-10-15 17:47 UTC, evantahler commented on data/authors.ts
> +  twitter?: string;
👍

2021-10-15 17:47 UTC, evantahler commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +  // Declare a new state variable, which we'll call "count"  const [count, setCount] = useState(0);
Why is this commented out, and not doing the `useState()`?

2021-10-15 17:47 UTC, evantahler commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +```
So is this part of the example of what I should do or what I shouldn't do?

2021-10-18 13:10 UTC, krishnaglick commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +```
I was throwing together some React docs stuff, plus modifying some code we have. I can improve it for sure.

2021-10-18 13:10 UTC, krishnaglick commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +  // Declare a new state variable, which we'll call "count"  const [count, setCount] = useState(0);
Copied react docs examples.

2021-10-18 20:58 UTC, evantahler approved these changes
Much clearer narrative!

This is ready-to-go as-is, but I've added some gramatical notes below

2021-10-18 20:58 UTC, evantahler commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +Managing data in a front-end framework is an infinitely solved problem. Every framework has its own flavor, architecture, and opinions. Notably, NextJS makes does not. They provide a variety of metho
`Notably, NextJS makes does not.` - not what?  Maybe `Notably, NextJS does not have it's own opinions and leaves that up to you and React.`

2021-10-18 20:58 UTC, evantahler commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +I ultimately went with React Contexts given the use-case of the application I was building here at Grouparoo.
... and they work on both the server and browser in some magic way?  They don't conflict?  Contexts know how to get out of the way on the server and be present for the client?

2021-10-18 20:58 UTC, evantahler commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +For some background, I was a Lead Engineer at iHeartMedia on a very high-traffic application. If you've ever visited a website for a radio station under the iHeart brand you've seen the result of my
of my team's (apostrophe) engineering efforts.

2021-10-18 20:58 UTC, evantahler commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +As the application rendered each portion of the tree it would need to fetch additional data to know what portions to render next. NextJS only offered async rendering at the top of the tree, and at th
https://github.com/reactwg/react-18/discussions/37_ - extra `_`

2021-10-18 20:58 UTC, evantahler commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +Since the application was rendered from a single point all application data was stored in a top level MobX store. This was dehydrated, shipped to the client, and then hydrated for application parity.
Maybe a link to https://en.wikipedia.org/wiki/Hydration_(web_development)

2021-10-18 20:58 UTC, evantahler commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +As seen above, I like to make use of React hooks extensively. Since hooks don't run on the server any logic I built to load and store data had to _also_ happen in a `getServerSideProps`, or other Nex
> Since hooks don't run on the server, any logic I built (comma)

2021-10-18 20:58 UTC, evantahler commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +The other concept I utilized was putting _all_ data into [contexts](https://reactjs.org/docs/context.html). With a client-only application it made sense; going to a new "page" required limited to no
had utilized in the past?

2021-10-19 13:55 UTC, krishnaglick commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +I ultimately went with React Contexts given the use-case of the application I was building here at Grouparoo.
Since I go into more detail later, I think nuking this one line is good.

2021-10-19 13:56 UTC, krishnaglick commented on pages/blog/2021-10-14-nextjs-and-data.mdx
> +Managing data in a front-end framework is an infinitely solved problem. Every framework has its own flavor, architecture, and opinions. Notably, NextJS makes does not. They provide a variety of metho
I've rephrased, lemme know what you think!

2021-10-20 16:37 UTC, evantahler approved these changes
Looks great! Ship it!

2021-10-20 20:04 UTC, merged