Changing fonts, fixing one minor typo in footer.tsx
grouparoo/www.grouparoo.com pull request #738
Opened 2021-10-26 19:54 UTC by krishnaglick

## Change description

Changing fonts to match Typography shown [here](https://www.figma.com/file/FSLlDL9yNhpyOCTGVaZE7K/Grouparoo-Moodboard?node-id=5%3A3)

## Checklists

### Development

- [X] Application changes have been tested appropriately

### Impact

- [X] Code follows company security practices and guidelines
- [X] Security impact of change has been considered
- [X] Performance impact of change has been considered
- [X] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [X] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [X] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-10-26 20:01 UTC, krishnaglick commented
React used to be very particular about falsy being returned as null. Seems to handle `&&` fine [now](https://reactjs.org/docs/conditional-rendering.html)

2021-10-26 20:24 UTC, teallarson requested changes
Nice!  And nice cleanup too.  

One thing I noticed is the weight, kerning, and line heights don't all match between the Figma file and what I see in the preview deployment.  The Figma file shows adjustments to character spacing in a few spots (headings are -1 to -0.44, overline(?) is 2), and it looks like h1s are "extra-bold" and a few of the classes have line heights of 150-170%. (These settings can be seen over in the "text" menu on the right if you select the component in Figma)

I'm not positive what Bootstrap's defaults are but I'm guessing those pieces are the mismatch!

<img width="905" alt="Screen Shot 2021-10-26 at 4 12 06 PM" src="https://user-images.githubusercontent.com/63751206/138953736-aaa4eccd-eb91-462f-a24f-fd4526d62de8.png">

I also noticed the code block color scheme, but I'm guessing that's part of a forthcoming theme/color update!

2021-10-26 20:24 UTC, teallarson commented on components/footer.tsx
> +                    <a>Redshift Integration</a>
nice

2021-10-28 15:46 UTC, teallarson approved these changes
Looks good!
<img width="1008" alt="Screen Shot 2021-10-28 at 11 45 16 AM" src="https://user-images.githubusercontent.com/63751206/139290487-b702e5dc-f079-4add-be4e-91dde1f2c8d8.png">

2021-10-28 15:56 UTC, krishnaglick commented on components/home/whoWeAre.tsx
> +          {teamMembers.map(({ emojis, previously, ...teamMemberProps }) => (
This diff looks really ugly but is just using a property over an index.

2021-10-28 16:52 UTC, krishnaglick commented on components/home/whoWeAre.tsx
> +          {teamMembers.map(({ emojis, previously, ...teamMemberProps }) => (
Keeping this change based on the [docs](https://reactjs.org/docs/lists-and-keys.html#keys) recommendation: `We don’t recommend using indexes for keys if the order of items may change.`

2021-10-28 17:05 UTC, andyjih approved these changes
👍  lgtm!

2021-10-28 18:08 UTC, merged