Add featured blog posts to header
grouparoo/www.grouparoo.com pull request #748
Opened 2021-10-28 19:36 UTC by evantahler

Show off our featured blog posts.

<img width="1356" alt="Screen Shot 2021-10-28 at 1 24 01 PM" src="https://user-images.githubusercontent.com/303226/139330226-fd360123-6516-43e0-afab-f3212d9a0eaf.png">

I did not go with a mechanism to "tag" posts we want as "featured" in the frontmatter so we could have explicit control of the links, titles, and order of the featured posts.  This also means we don't need to pre-hydrate every page with a filesystem read. 

The story asked for a new blog section in the footer, but I thought it was getting really crowded.  To that end, I added the blog posts to the "Use Cases" section.  

<img width="843" alt="Screen Shot 2021-10-28 at 1 23 51 PM" src="https://user-images.githubusercontent.com/303226/139330247-c6d2412d-6f92-4ab5-8d19-e949c1a18cb7.png">
<img width="1356" alt="Screen Shot 2021-10-28 at 1 23 54 PM" src="https://user-images.githubusercontent.com/303226/139330253-492274f5-1212-4cdb-924f-278a1b3fb85d.png">
## Checklists

### Development

- [ ] Application changes have been tested appropriately

### Impact

- [x] Code follows company security practices and guidelines
- [x] Security impact of change has been considered
- [x] Performance impact of change has been considered
- [x] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [x] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-10-28 21:25 UTC, teallarson requested changes
Looks good!  That's a good place for those posts in the footer too.

There is this unexpected behavior on tablet screens with the menu overflowing the frame. 
<img width="391" alt="Screen Shot 2021-10-28 at 5 23 31 PM" src="https://user-images.githubusercontent.com/63751206/139337657-526675f1-be83-48e2-b14a-49c011b38099.png">

2021-10-28 22:27 UTC, evantahler commented
I couldn't decide what to do about an overflow on a fixed viewport... do we hide the overflow?  wrap the words?

So... I just hid "blog", and brought back "solutions" on the tablet size :D

2021-10-29 16:17 UTC, andyjih requested changes
Nice! 

1. Could these line up?
![2021-10-29_09-04-16](https://user-images.githubusercontent.com/633226/139467528-28ead7ed-27eb-41c7-9eed-0690d8e05399.png)

2. Could the dropdown expand to the left? That might address the tablet layout issues. The idea being the right-side of the dropdown box would right-align with the `Blog` link. Just an idea though. What you're doing now is also cool.

2021-10-29 16:20 UTC, evantahler commented
All of the other drop downs have the header and icon over to the left a bit - I think we should keep them the same.  Want me to change all of them if I can?

<img width="271" alt="Screen Shot 2021-10-29 at 9 19 52 AM" src="https://user-images.githubusercontent.com/303226/139469060-e4026637-c388-49d3-b82f-3dbbf2c72c0c.png">.

The width of the dropdown is determined by the container, so the tablet layout was fixed by hiding it :D

2021-10-29 16:31 UTC, andyjih approved these changes

2021-10-29 16:31 UTC, andyjih commented
ok then!

2021-10-29 19:54 UTC, tealjulia approved these changes

2021-10-29 19:54 UTC, merged