Upgrade Bootstrap
grouparoo/www.grouparoo.com pull request #790
Opened 2021-11-23 17:03 UTC by krishnaglick

## Change description
Upgrading Bootstrap

Some migration docs:
https://react-bootstrap.github.io/migrating/#summary-of-breaking-changes-from-v1x
https://getbootstrap.com/docs/5.0/migration/

![Screen Shot 2021-11-23 at 12 01 49 PM](https://user-images.githubusercontent.com/4967694/143070075-76a5215b-e2d9-4a8b-9902-495cf58e005d.png)

There's some differences but most of them are minor. I would like to point out that Button Text is black instead of white. I haven't been able to determine precisely why, or what needs overriding to make it white. But with the UI refresh looming I feel it may not be worth the effort.

## Checklists

### Development

- [ ] Application changes have been tested appropriately

### Impact

- [ ] Code follows company security practices and guidelines
- [ ] Security impact of change has been considered
- [ ] Performance impact of change has been considered
- [ ] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [ ] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-11-23 17:08 UTC, krishnaglick commented on components/Subscribe.tsx
> +        <Row className="p-2">
I think overall padding/margin was altered for Row/Col, so this just makes things look fine.

2021-11-23 18:18 UTC, evantahler requested changes
Awesome! I think getting up-to-date will be really important.  I also agree that in most cases we aren't trying for a pixel-perfect match, but that the styles overall /feel/ the same.

Interesting notes:
* The max container width got bigger!  Some responsive things are bigger now

Things to fix:
* Side nav (docs) links are now underlined.  They should not be. (1) 
* Markdown (docs) in-page links are now underlines.  The should not be.
* blog follow box's form and button are no-longer left aligned (2)
* Integrations bar is wonky (3)
* I think the black button text is odd... I like the white :D 
* Meet form missing padding around the submit button (4)
* Checkbox on form not near works (5)

1.
<img width="361" alt="Screen Shot 2021-11-23 at 10 14 19 AM" src="https://user-images.githubusercontent.com/303226/143081098-bcd88e39-189b-4a96-890e-71e56760d7b2.png">

2.
<img width="380" alt="Screen Shot 2021-11-23 at 10 13 26 AM" src="https://user-images.githubusercontent.com/303226/143081047-b0afa80c-31c8-403e-a9c2-58f8cc3e897c.png">

3.
<img width="1290" alt="Screen Shot 2021-11-23 at 10 14 54 AM" src="https://user-images.githubusercontent.com/303226/143081220-7cd08f92-2972-4b54-b921-ffe38908b608.png">

4.
<img width="661" alt="Screen Shot 2021-11-23 at 10 16 09 AM" src="https://user-images.githubusercontent.com/303226/143081376-ef7396eb-8019-4a2e-b4ed-487938e1a3d6.png">

5.
<img width="696" alt="Screen Shot 2021-11-23 at 10 16 46 AM" src="https://user-images.githubusercontent.com/303226/143081458-88b59393-560f-4dd7-8d08-eff810e58c8f.png">

2021-11-23 18:18 UTC, evantahler commented on pages/_app.tsx
> +import SSRProvider from "react-bootstrap/SSRProvider";
neat https://react-bootstrap.github.io/getting-started/server-side-rendering/

2021-11-23 18:50 UTC, tealjulia reviewed
I'll defer to Evan here overall, but nice!

I wonder if the default text for the buttons is related to Bootstrap 5 [changing its default contrast ratio](https://getbootstrap.com/docs/5.0/migration/#color-system).  Our buttons didn't have a great contrast ratio before (though I did like them better). But I'm sure they're likely to change here soon with the site update.

Just for reference in case anyone else is interested:

before: 
<img width="811" alt="Screen Shot 2021-11-23 at 1 45 37 PM" src="https://user-images.githubusercontent.com/63751206/143085142-8ce49565-9c8b-4254-8a3b-277780e3514b.png">
(ideal is 4.5 or greater)
 
now:
<img width="772" alt="Screen Shot 2021-11-23 at 1 46 14 PM" src="https://user-images.githubusercontent.com/63751206/143085233-46625ef6-a89e-40f0-81ce-d67a6f460f60.png">

2021-11-23 18:54 UTC, krishnaglick commented
Regarding Button text color, it's going to be black in the new UI. Maybe worth just leaving as is? I do think it's black due to contract/a11y things.

2021-11-23 18:55 UTC, evantahler commented
> Regarding Button text color, it's going to be black in the new UI. Maybe worth just leaving as is? I do think it's black due to contract/a11y things.

Sure, leave it back then!

2021-11-23 20:19 UTC, krishnaglick commented
I've got everything handled, except on the Trial pages this checkbox is slightly off "center".

![Screen Shot 2021-11-23 at 3 18 46 PM](https://user-images.githubusercontent.com/4967694/143097688-ad42a630-3fe4-41b3-a442-d8528e194016.png)

2021-11-23 20:32 UTC, krishnaglick commented
> I've got everything handled, except on the Trial pages this checkbox is slightly off "center".
> 
> ![Screen Shot 2021-11-23 at 3 18 46 PM](https://user-images.githubusercontent.com/4967694/143097688-ad42a630-3fe4-41b3-a442-d8528e194016.png)

Wrapped the checkbox in a small. :| It works

2021-11-23 21:23 UTC, evantahler approved these changes
Nice!

The integrations links are certainly different now... but the padding is nice!
<img width="1749" alt="Screen Shot 2021-11-23 at 1 23 16 PM" src="https://user-images.githubusercontent.com/303226/143131386-703e0765-0baa-4230-b3d4-569753e28d0f.png">

2021-11-23 21:34 UTC, tealjulia commented
> Nice!
> 
> The integrations links are certainly different now... but the padding is nice! <img alt="Screen Shot 2021-11-23 at 1 23 16 PM" width="1749" src="https://user-images.githubusercontent.com/303226/143131386-703e0765-0baa-4230-b3d4-569753e28d0f.png">

The columns are off-center with the text but I don't think it's blocking

2021-11-23 21:35 UTC, tealjulia approved these changes

2021-11-24 14:33 UTC, krishnaglick commented
![Screen Shot 2021-11-24 at 9 32 41 AM](https://user-images.githubusercontent.com/4967694/143257614-d984329a-4754-4545-bab0-db56f70fd872.png)

@tealjulia @evantahler How do you feel about a really wide button?

2021-11-24 15:27 UTC, tealjulia commented
> ![Screen Shot 2021-11-24 at 9 32 41 AM](https://user-images.githubusercontent.com/4967694/143257614-d984329a-4754-4545-bab0-db56f70fd872.png)
> 
> @tealjulia @evantahler How do you feel about a really wide button?

Mildly negative but mostly neutral.  This component has driven me nuts a few times trying to get things to line up just right!

2021-11-24 15:31 UTC, krishnaglick commented
> > ![Screen Shot 2021-11-24 at 9 32 41 AM](https://user-images.githubusercontent.com/4967694/143257614-d984329a-4754-4545-bab0-db56f70fd872.png)
> > @tealjulia @evantahler How do you feel about a really wide button?
> 
> Mildly negative but mostly neutral. This component has driven me nuts a few times trying to get things to line up just right!

Okay, just going to merge then. Will will be through here at some point and we can fix it then!

2021-11-24 15:31 UTC, merged