Remove Manual Groups
grouparoo/www.grouparoo.com pull request #828
Opened 2021-12-16 04:57 UTC by evantahler

Remove manual Groups (do not merge until after https://github.com/grouparoo/grouparoo/pull/2681 is merged)

## Checklists

### Development

- [ ] Application changes have been tested appropriately

### Impact

- [ ] Code follows company security practices and guidelines
- [ ] Security impact of change has been considered
- [ ] Performance impact of change has been considered
- [ ] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [ ] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-12-16 17:07 UTC, andyjih requested changes
Just a small tweak, but looks good!

2021-12-16 17:07 UTC, andyjih commented on pages/docs/config/code-config/groups.mdx
> +Groups are where the magic happens in Grouparoo. (It's in the name, after all!) Groups are a segment or cohort of Records. They are useful in that you can use Groups to target a specific set of users
```suggestion
Groups are where the magic happens in Grouparoo. (It's in the name, after all!) Groups are a segment or cohort of Records. They are useful in that you can use Groups to target a specific set of models to [export to some Destination](/docs/running/ui-enterprise/destinations). [See here](/docs/getting-started/product-concepts) to learn more about the core concepts in Grouparoo.
```

2021-12-16 17:07 UTC, andyjih commented on pages/docs/config/groups.mdx
> +Groups are where the magic happens in Grouparoo. (It's in the name, after all!) Groups are a segment or cohort of Records. They are useful in that you can use Groups to target a specific set of users
```suggestion
Groups are where the magic happens in Grouparoo. (It's in the name, after all!) Groups are a segment or cohort of Records. They are useful in that you can use Groups to target a specific set of models to [export to some Destination](/docs/config/destinations). [See here](/docs/getting-started/product-concepts) to learn more about the core concepts in Grouparoo.
```

2021-12-16 22:44 UTC, andyjih approved these changes

2021-12-17 12:08 UTC, tealjulia approved these changes
Bye, manual groups!

2021-12-17 12:08 UTC, tealjulia commented on pages/docs/config/code-config/groups.mdx
> +Configuring a Group is all about adding Rules to the Group. A Rule is some logical operator to Filter Properties. A Record must match every Rule to be included in the Group.
non-blocking nitpick:
```suggestion
Configuring a Group is all about adding Rules to the Group. A Rule is some logical operator to filter Properties. A Record must match every Rule to be included in the Group.
```

2021-12-21 19:03 UTC, merged