180864002 SQLite Integration and minor edits for SendGrid
grouparoo/www.grouparoo.com pull request #875
Opened 2022-01-14 15:23 UTC by Adorism

## Change description

This is the new SQLite integration page with source and destination information as well as a few minor edits to SendGrid for clarity and consistency in capitalization convention. 

## Checklists

### Development

- [ ] Application changes have been tested appropriately

### Impact

- [ ] Code follows company security practices and guidelines
- [ ] Security impact of change has been considered
- [ ] Performance impact of change has been considered
- [ ] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [ ] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2022-01-18 15:06 UTC, tealjulia requested changes
Nice!  These docs are really coming along.  A little cleanup work and a few questions.  In general, I also think it's helpful to capitalize our Grouparoo product concepts (Schedules, Sources, Filters, etc.) for user clarity.

2022-01-18 15:06 UTC, teallarson commented on pages/docs/integrations/grouparoo-sqlite.mdx
> +    <a href="#sqlite-export-record">
Broken link.  Looks like the heading text below needs changed.

2022-01-18 15:06 UTC, teallarson commented on pages/docs/integrations/grouparoo-sqlite.mdx
> +      This should be the Absolute path of the SQLite database file you want to
```suggestion
      This should be the Absolute path of the SQLite database file you want to
```
```suggestion
      This should be the absolute path of the SQLite database file you want to
```

2022-01-18 15:06 UTC, teallarson commented on pages/docs/integrations/grouparoo-sqlite.mdx
> +<ImageInBrowserFrame
I wonder if we want to use the general `<Image>` component (no browser frame) for these since they're only showing a partial screen.  What do you think?

2022-01-18 15:06 UTC, teallarson commented on pages/docs/integrations/grouparoo-sqlite.mdx
> +
Oops, line break

2022-01-18 15:06 UTC, teallarson commented on pages/docs/integrations/grouparoo-sqlite.mdx
> +## SQLite Import Query
For table imports, you demonstrated how to create Properties.  I wonder if it makes sense to do it for both import types (or neither)?

2022-01-18 15:06 UTC, teallarson commented on pages/docs/integrations/grouparoo-sqlite.mdx
> +## SQLite Export Contacts
There's some cleaning up to do in this section -- mentions of Contacts and Intercom.

2022-01-18 15:47 UTC, Adorism commented on pages/docs/integrations/grouparoo-sqlite.mdx
> +## SQLite Import Query
Yes, eventually I will come back to the Query sections. For now, we decided to leave this as is because of a blocker and have a basic overview in place until I can proceed.

2022-01-18 15:50 UTC, Adorism commented on pages/docs/integrations/grouparoo-sqlite.mdx
> +## SQLite Export Contacts
got it, thanks!

2022-01-18 15:50 UTC, Adorism commented on pages/docs/integrations/grouparoo-sqlite.mdx
> +    <a href="#sqlite-export-record">
Fixed. Yep, just a differently named heading.

2022-01-18 16:05 UTC, Adorism commented on pages/docs/integrations/grouparoo-sqlite.mdx
> +<ImageInBrowserFrame
I think I am going to stick with this for now, based on conversations I have had thinking about it earlier. It might change.

2022-01-18 22:14 UTC, andyjih approved these changes

2022-01-18 22:14 UTC, andyjih commented on pages/docs/integrations/grouparoo-sendgrid.mdx
>  date: "2022-1-10"
```suggestion
date: "2022-01-10"
```

2022-01-18 22:14 UTC, andyjih commented on pages/docs/integrations/grouparoo-sqlite.mdx
> +date: "2022-1-14"
```suggestion
date: "2022-01-14"
```

2022-01-19 18:41 UTC, tealjulia approved these changes

2022-01-19 18:42 UTC, merged