Blog: v0.8 release
grouparoo/www.grouparoo.com pull request #896
Opened 2022-02-01 00:26 UTC by bleonard

## Change description

Adds blog post and video about new release.

## Checklists

### Development

- [ ] Application changes have been tested appropriately

### Impact

- [ ] Code follows company security practices and guidelines
- [ ] Security impact of change has been considered
- [ ] Performance impact of change has been considered
- [ ] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [ ] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2022-02-01 16:41 UTC, evantahler approved these changes
Some minor word suggestions, but 👍!

2022-02-01 16:41 UTC, evantahler commented on pages/blog/v08-release.mdx
> +The v0.8 release is our first major iteration on the UI for creating your data pipeline. In the v0.7 release, we added Models, which allowed data engineers to sync multiple data schemas to Destinatio
```suggestion
The v0.8 release is our first major iteration on the user interface for creating your data pipeline. In the v0.7 release, we added Models, which allowed data engineers to sync multiple data schemas to Destinations. This release summarizes those Models better in the UI, giving you a clearer overview of the configuration, making it quicker and easier to sync your data.
```

2022-02-01 16:41 UTC, evantahler commented on pages/blog/v08-release.mdx
> +- Upgrade to Google Sheets Source to act more like SQL Sources
```suggestion
- Upgraded to Google Sheets Source to act more like SQL Sources
```

2022-02-01 16:41 UTC, evantahler commented on pages/blog/v08-release.mdx
> +## Model UI
```suggestion
## Grouparoo User Interface
```

2022-02-01 16:41 UTC, evantahler commented on pages/blog/v08-release.mdx
> +
Maybe add a screenshot below the video too?

2022-02-01 16:41 UTC, evantahler commented on pages/blog/v08-release.mdx
> +Now, you can add those `NULL`-ish filters as you like.
```suggestion
Now, you can add those `NULL`-ish (and non-`NULL`-ish) filters as you like.
```

2022-02-01 17:17 UTC, andyjih requested changes
Minor comments, but looking good!

2022-02-01 17:17 UTC, andyjih commented on pages/blog/v08-release.mdx
> +- Model-centric UI to see on one page where the data comes from, what it looks like, and where it is going
Not major: I wonder if "Model-centric UI" is too much of an internal term or phrasing.
"Model-based UI"
"Model-focused UI"

Wondering if maybe I'm too close to it though.

2022-02-01 17:17 UTC, andyjih commented on pages/blog/v08-release.mdx
> +As a piece of this, we have also upgraded the sample Record portion of the Model overview. In the open source Config UI, we now automatically add sample Records so it is easier to visualize your sche
```suggestion
As a piece of this update, we have also upgraded the sample Record portion of the Model overview. In the open source Config UI, we now automatically add sample Records so it is easier to visualize your schema.
```

2022-02-01 17:17 UTC, andyjih commented on pages/blog/v08-release.mdx
> +[Google Sheets](https://www.google.com/sheets/about/) now acts more like SQL Sources. For example, this allows it to work better in fetching single rows from the sheet, keeping your data more consist
```suggestion
[Google Sheets](https://www.google.com/sheets/about/) now acts more like SQL Sources like MySQL and PostgresQL. For example, this update allows the plugin to work better in fetching single rows from the sheet, keeping your data more consistent.
```

2022-02-02 00:44 UTC, andyjih approved these changes

2022-02-02 01:00 UTC, merged